### ISSUE TITLE
build failing

### ISSUE THREAD

**Issue by ranajit-jana** [jboss-integration/kie-eap-modules#6]
build fails with following error.

[INFO] ------------------------------------------------------------------------
[INFO] Building BxMS Fuse Integration: Config 7.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: https://repository.jboss.org/nexus/content/groups/public/com/redhat/fuse/fuse-eap-config/6.2.0.redhat-124/fuse-eap-config-6.2.0.redhat-124.pom
Downloading: https://repo.fusesource.com/nexus/content/groups/ea/com/redhat/fuse/fuse-eap-config/6.2.0.redhat-124/fuse-eap-config-6.2.0.redhat-124.pom
Downloading: https://repo.maven.apache.org/maven2/com/redhat/fuse/fuse-eap-config/6.2.0.redhat-124/fuse-eap-config-6.2.0.redhat-124.pom
[WARNING] The POM for com.redhat.fuse:fuse-eap-config:jar:6.2.0.redhat-124 is missing, no dependency information available
Downloading: https://repository.jboss.org/nexus/content/groups/public/com/redhat/fuse/fuse-eap-config/6.2.0.redhat-124/fuse-eap-config-6.2.0.redhat-124.jar
Downloading: https://repo.fusesource.com/nexus/content/groups/ea/com/redhat/fuse/fuse-eap-config/6.2.0.redhat-124/fuse-eap-config-6.2.0.redhat-124.jar
Downloading: https://repo.maven.apache.org/maven2/com/redhat/fuse/fuse-eap-config/6.2.0.redhat-124/fuse-eap-config-6.2.0.redhat-124.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 17.175 s
[INFO] Finished at: 2016-01-23T22:22:45+05:30
[INFO] Final Memory: 42M/1963M

**Comment by psiroky** [comment]
Thanks for reporting this. We are trying to fix it (it is not just about bumping the version, API of that dependency completely changed, so we need code changes as well).

**Comment by psiroky** [comment]
Well, it took us long enough, but the build is now fixed.

**Comment by ranajit-jana** [comment]
Build successful with new code. Thank you
